export type Gender = 'men' | 'women'

export interface Team {
  id: string
  name: string
  short_name: string
  gender: Gender
  logo_url: string
  matches: number
  fairplay_points: number
  /** Generated by Postgres: fairplay_points / matches, 0 when unplayed. */
  avg_fp: number
  updated_at: string
}

/** Only the columns an admin is granted UPDATE on. */
export type TeamEdit = Pick<Team, 'name' | 'logo_url' | 'matches' | 'fairplay_points'>

export const GENDERS: Gender[] = ['men', 'women']

export const GENDER_LABELS: Record<Gender, string> = {
  men: "Men's",
  women: "Women's",
}

export const GENDER_TITLES: Record<Gender, string> = {
  men: "Men's Fairplay Standings",
  women: "Women's Fairplay Standings",
}

export const SEASON = 'Season 04'

export function isGender(value: string | undefined): value is Gender {
  return value === 'men' || value === 'women'
}
